# -=-=-= SELECT =-=-=-
GET http://localhost:3000/produto HTTP/1.1
Content-Type: application/json
###


GET http://localhost:3000/produto/buscapreco/15.25 HTTP/1.1
Content-Type: application/json
###

# -=-=-= INSERT =-=-=-
POST http://localhost:3000/produto HTTP/1.1
Content-Type: application/json

{
    "cod_produto": 3,
    "nome_produto": "Arroz",
    "preco_produto": 5.75
}
### 

# -=-=-= UPDATE GERAL =-=-=-
PUT http://localhost:3000/produto/1 HTTP/1.1
Content-Type: application/json

{
    "nome_produto": "Feijao",
    "preco_produto": 7.25
}
###

# -=-=-= UPDATE NOME =-=-=-
PUT http://localhost:3000/produto/nome/2 HTTP/1.1
# Content-Type: application/json

{
    "nome_produto": "Carne"
}
###

# -=-=-= UPDATE PRECO =-=-=-
PUT http://localhost:3000/produto/preco/3 HTTP/1.1
Content-Type: application/json

{
    "preco_produto": 9.99
}
###

# -=-=-= DELETE =-=-=-
# CABEÇALHO (HEAD) DA REQUISIÇÃO
DELETE http://localhost:3000/produto/3 HTTP/1.1
Content-Type: application/json



